/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#00665d",
        "on-secondary-container": "#54647a",
        "on-primary-container": "#e5fffa",
        "primary-fixed-dim": "#6bd8cb",
        "secondary-fixed": "#d3e4fe",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#006a61",
        "secondary": "#505f76",
        "surface": "#f7f9fb",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed": "#0b1c30",
        "primary-fixed": "#89f5e7",
        "surface-container-high": "#e6e8ea",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#e8ffef",
        "on-primary-fixed-variant": "#005049",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "tertiary-container": "#00835a",
        "inverse-primary": "#6bd8cb",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "outline-variant": "#bdc9c8",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed": "#002113",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary": "#006746",
        "surface-container-low": "#f2f4f6",
        "primary-container": "#008176",
        "on-surface-variant": "#3e4949",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#d0e1fb",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "outline": "#6e7979",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container": "#eceef0",
        "on-error-container": "#93000a",
        "background": "#f7f9fb"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "1.5rem", "full": "9999px" },
    },
  },
  plugins: [],
};
